### ISSUE TITLE
Make it json

### ISSUE THREAD

**Issue by WoozyDev** [culturally/critical-ops-bot#1]
You can put the "Content-Type" to application/json to get json response bruh.

**Comment by WoozyDev** [comment]
```python
    response = requests.get(url, headers={"Content-Type":"application/json"})
```

**Comment by culturally** [comment]
yea I know it's even in the readme but considering i didn't use json and wasted hours of trying to figure out how it works now i don't wanna use json and recode it again

**Comment by WoozyDev** [comment]
i can make a pull request
